### ISSUE TITLE
add 32-bit support

### ISSUE THREAD

**Issue by dosgo** [birros/go-wasm3#4]
![image](https://user-images.githubusercontent.com/9545458/137856548-2739cfe1-3b38-4f91-b8ee-e1053e0f2823.png)
Do you have any ideas to increase 32-bit support? Currently the compilation fails!

**Comment by dosgo** [comment]
I need tomorrow, and it's wee hours for me now.

**Comment by dosgo** [comment]
![image](https://user-images.githubusercontent.com/9545458/138018558-46865b2c-d974-44a4-a2f0-c69497d723ce.png)
MaxUint16 can be compiled and passed, but no problems were found. I didn't understand the meaning of this line. Why can't I use len(args)?

**Comment by birros** [comment]
Done, however I kept the slice, instead of initializing a huge slice, I use `reflect.SliceHeader` to create a slice the size of the array in C.
